{{- if .Values.config.createConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataspoke.fullname" . }}-app-config
  labels:
    {{- include "dataspoke.labels" . | nindent 4 }}
data:
  DATASPOKE_POSTGRES_HOST: {{ .Values.config.postgres.host | quote }}
  DATASPOKE_POSTGRES_PORT: {{ .Values.config.postgres.port | quote }}
  DATASPOKE_POSTGRES_DB: {{ .Values.config.postgres.db | quote }}
  DATASPOKE_REDIS_HOST: {{ .Values.config.redis.host | quote }}
  DATASPOKE_REDIS_PORT: {{ .Values.config.redis.port | quote }}
  DATASPOKE_AIRFLOW_URL: {{ .Values.config.airflow.url | quote }}
  DATASPOKE_AIRFLOW_CALLBACK_BASE_URL: {{ .Values.config.airflow.callbackBaseUrl | quote }}
  DATASPOKE_CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
{{- end }}
