# PR lifecycle operations for prauto.
# Source this file — do not execute directly.
# Requires: helpers.sh sourced, state.sh sourced, claude.sh sourced, config loaded, gh/git available.

# Create or update a PR for the given issue.
# Usage: create_or_update_pr <issue_number> <issue_title> <branch>
create_or_update_pr() {
  local issue_number="$1"
  local issue_title="$2"
  local branch="$3"

  # Check for existing PR
  local existing_pr
  existing_pr=$(gh pr list \
    -R "$PRAUTO_GITHUB_REPO" \
    --head "$branch" \
    --json number \
    --jq '.[0].number // empty' 2>/dev/null)

  if [[ -n "$existing_pr" ]]; then
    info "PR #${existing_pr} already exists for ${branch}. Adding update comment."
    local commit_log
    commit_log=$(git log --oneline "origin/${PRAUTO_BASE_BRANCH}..HEAD" 2>/dev/null || echo "(no commits)")
    gh pr comment "$existing_pr" -R "$PRAUTO_GITHUB_REPO" \
      --body "prauto(${PRAUTO_WORKER_ID}): Updated with new commits.

\`\`\`
${commit_log}
\`\`\`" 2>/dev/null || warn "Failed to comment on PR #${existing_pr}."
    return 0
  fi

  # Generate PR body
  local commit_log
  commit_log=$(git log --oneline "origin/${PRAUTO_BASE_BRANCH}..HEAD" 2>/dev/null || echo "(no commits)")

  local pr_body
  pr_body="## Summary

Automated implementation for #${issue_number}.
Generated by \`prauto(${PRAUTO_WORKER_ID})\` using Claude Code CLI.

## Changes

\`\`\`
${commit_log}
\`\`\`

---
*Generated by prauto -- autonomous PR worker*"

  # Build optional flags
  local reviewer_flag=()
  if [[ -n "${PRAUTO_REVIEWER:-}" ]]; then
    reviewer_flag=(--reviewer "$PRAUTO_REVIEWER")
  fi

  info "Creating PR for issue #${issue_number}..."
  gh pr create \
    -R "$PRAUTO_GITHUB_REPO" \
    --base "$PRAUTO_BASE_BRANCH" \
    --head "$branch" \
    --title "${issue_title}" \
    --body "$pr_body" \
    --assignee "${PRAUTO_GITHUB_ACTOR}" \
    --label "${PRAUTO_GITHUB_LABEL_REVIEW}" \
    "${reviewer_flag[@]}" || error "Failed to create PR for ${branch}."

  info "PR created for issue #${issue_number}."
}

# Check PR status for a prauto:review issue and determine the next action.
# Priority: squash-finalize (approved+clean) > address feedback > waiting.
# Usage: check_review_pr <issue_number>
# Sets: REVIEW_PR_NUMBER, REVIEW_PR_BRANCH, REVIEW_PR_ACTION ("squash_ready"|"feedback_needed")
#       REVIEW_PR_TITLE, REVIEW_PR_BODY (for squash_ready)
#       ACTIONABLE_COMMENTS (for feedback_needed)
# Returns 0 if actionable, 1 if waiting/no-pr.
check_review_pr() {
  local issue_number="$1"
  REVIEW_PR_BRANCH="${PRAUTO_BRANCH_PREFIX}I-${issue_number}"
  REVIEW_PR_ACTION=""

  # Find PR for this branch
  local pr_list_json
  pr_list_json=$(gh pr list -R "$PRAUTO_GITHUB_REPO" --head "$REVIEW_PR_BRANCH" \
    --json number,title,body --jq '.[0] // empty' 2>/dev/null)
  [[ -z "$pr_list_json" ]] && return 1

  REVIEW_PR_NUMBER=$(echo "$pr_list_json" | jq -r '.number')
  REVIEW_PR_TITLE=$(echo "$pr_list_json" | jq -r '.title')
  REVIEW_PR_BODY=$(echo "$pr_list_json" | jq -r '.body // ""')

  # Single detailed PR fetch (used by both squash and feedback checks)
  local pr_detail
  pr_detail=$(gh pr view "$REVIEW_PR_NUMBER" -R "$PRAUTO_GITHUB_REPO" \
    --json mergeable,mergeStateStatus,reviews 2>/dev/null) || pr_detail=""

  # --- Priority 1: Check squash-ready (approved + MERGEABLE + CLEAN) ---
  if [[ -n "$pr_detail" ]] && fetch_org_members 2>/dev/null; then
    local mergeable merge_state
    mergeable=$(echo "$pr_detail" | jq -r '.mergeable')
    merge_state=$(echo "$pr_detail" | jq -r '.mergeStateStatus')

    local approver
    approver=$(echo "$pr_detail" | jq -r --argjson members "$ORG_MEMBERS_JSON" '
      (.reviews // [])
      | map(select(.author.login as $a | $members | index($a) != null))
      | group_by(.author.login)
      | map(sort_by(.submittedAt) | last)
      | map(select(.state == "APPROVED"))
      | first // empty
      | .author.login // empty')

    if [[ -n "$approver" ]] && [[ "$mergeable" == "MERGEABLE" ]] && [[ "$merge_state" == "CLEAN" ]]; then
      REVIEW_PR_ACTION="squash_ready"
      info "PR #${REVIEW_PR_NUMBER}: approved by '${approver}', mergeable, clean → squash-ready."
      return 0
    fi
  fi

  # --- Priority 2: Check feedback-needed (unaddressed reviewer comments) ---
  local pr_review_comments pr_issue_comments
  pr_review_comments=$(gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${REVIEW_PR_NUMBER}/comments" \
    --jq '[.[] | {id: .id, body: .body, user: .user.login, created_at: .created_at}]' \
    2>/dev/null || echo "[]")
  pr_issue_comments=$(gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${REVIEW_PR_NUMBER}/comments" \
    --jq '[.[] | {id: .id, body: .body, user: .user.login, created_at: .created_at}]' \
    2>/dev/null || echo "[]")

  # Skip if feedback already addressed and no newer comments
  local latest_prauto_body latest_prauto_time
  latest_prauto_body=$(echo "$pr_issue_comments" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" '
    [.[] | select(.user == $actor)] | sort_by(.created_at) | last | .body // ""')
  latest_prauto_time=$(echo "$pr_issue_comments" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" '
    [.[] | select(.user == $actor)] | sort_by(.created_at) | last | .created_at // ""')

  if echo "$latest_prauto_body" | grep -q "Reviewer feedback addressed"; then
    local newer_issue newer_reviews
    newer_issue=$(echo "$pr_issue_comments" | jq --arg actor "$PRAUTO_GITHUB_ACTOR" --arg ts "$latest_prauto_time" '
      [.[] | select(.user != $actor) | select(.created_at > $ts)] | length')
    newer_reviews=$(echo "$pr_review_comments" | jq --arg ts "$latest_prauto_time" '
      [.[] | select(.created_at > $ts)] | length')
    if [[ "$newer_issue" -eq 0 ]] && [[ "$newer_reviews" -eq 0 ]]; then
      info "PR #${REVIEW_PR_NUMBER}: feedback already addressed. Waiting."
      return 1
    fi
    info "PR #${REVIEW_PR_NUMBER}: new comments after marker. Re-evaluating."
  fi

  # Merge both comment sources
  local all_comments
  all_comments=$(jq -s 'add' <<< "${pr_review_comments}${pr_issue_comments}" 2>/dev/null || echo "[]")

  # Find non-prauto comments
  local unaddressed unaddressed_count
  unaddressed=$(echo "$all_comments" | jq -r --arg worker "prauto(${PRAUTO_WORKER_ID})" '
    [.[] | select(.body | startswith($worker) | not)]')
  unaddressed_count=$(echo "$unaddressed" | jq 'length')

  # Check for review signal (formal review or external comments)
  local has_review_signal=false
  if [[ -n "$pr_detail" ]]; then
    local has_review
    has_review=$(echo "$pr_detail" | jq \
      '[(.reviews // [])[] | select(.state == "CHANGES_REQUESTED" or .state == "COMMENTED")] | length > 0')
    [[ "$has_review" == "true" ]] && has_review_signal=true
  fi
  if [[ "$has_review_signal" == "false" ]] && [[ "$unaddressed_count" -gt 0 ]]; then
    local external_count
    external_count=$(echo "$unaddressed" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" '
      [.[] | select(.user != $actor)] | length')
    [[ "$external_count" -gt 0 ]] && has_review_signal=true
  fi

  if [[ "$unaddressed_count" -gt 0 ]] && [[ "$has_review_signal" == "true" ]]; then
    ACTIONABLE_COMMENTS=$(echo "$all_comments" | jq -r --arg worker "prauto(${PRAUTO_WORKER_ID})" '
      [.[] | select(.body | startswith($worker) | not)]
      | map("Comment by \(.user):\n\(.body)")
      | join("\n\n---\n\n")')
    REVIEW_PR_ACTION="feedback_needed"
    info "PR #${REVIEW_PR_NUMBER}: unaddressed comments → feedback needed."
    return 0
  fi

  info "PR #${REVIEW_PR_NUMBER}: waiting for review."
  return 1
}

# Squash all commits on the PR branch into one, force-push, and mark as done.
# Does NOT merge the PR or close the issue — leaves that for the human.
# Rebuilds the commit message via Claude based on the issue description and git diff.
# Must be called from inside the worktree (checkout_branch_worktree already ran).
# Usage: squash_and_finalize_pr <pr_number> <pr_branch> <pr_title> <pr_body> <issue_number>
squash_and_finalize_pr() {
  local pr_number="$1"
  local pr_branch="$2"
  local pr_title="$3"
  local pr_body="$4"
  local issue_number="$5"

  # Export git identity for ALL subprocesses (rebase, commit, amend).
  # Exporting here (not per-command) ensures git's internal re-invocations also
  # pick up the prauto identity rather than the system git config.
  export GIT_AUTHOR_NAME="$PRAUTO_GIT_AUTHOR_NAME"
  export GIT_AUTHOR_EMAIL="$PRAUTO_GIT_AUTHOR_EMAIL"
  export GIT_COMMITTER_NAME="$PRAUTO_GIT_AUTHOR_NAME"
  export GIT_COMMITTER_EMAIL="$PRAUTO_GIT_AUTHOR_EMAIL"

  # Fetch base branch
  git fetch origin "$PRAUTO_BASE_BRANCH" 2>/dev/null || {
    warn "PR #${pr_number}: git fetch failed."
    return 1
  }

  # Rebase onto base branch
  if ! git rebase "origin/${PRAUTO_BASE_BRANCH}" 2>/dev/null; then
    warn "PR #${pr_number}: rebase onto origin/${PRAUTO_BASE_BRANCH} failed. Aborting."
    git rebase --abort 2>/dev/null || true
    return 1
  fi

  # Find merge base and count commits to squash
  local merge_base
  merge_base=$(git merge-base HEAD "origin/${PRAUTO_BASE_BRANCH}" 2>/dev/null) || {
    warn "PR #${pr_number}: could not find merge base."
    return 1
  }

  # Fetch issue description for commit message generation
  local issue_title issue_body
  issue_title=$(gh issue view "$issue_number" -R "$PRAUTO_GITHUB_REPO" \
    --json title --jq '.title // ""' 2>/dev/null || echo "")
  issue_body=$(gh issue view "$issue_number" -R "$PRAUTO_GITHUB_REPO" \
    --json body --jq '.body // ""' 2>/dev/null || echo "")

  # Gather diff info for Claude
  local diff_stat diff_content
  diff_stat=$(git diff --stat "${merge_base}..HEAD" 2>/dev/null || echo "(no diff stat)")
  diff_content=$(git diff "${merge_base}..HEAD" 2>/dev/null || echo "(no diff)")

  # Generate commit message via Claude (Phase 4)
  generate_squash_commit_message \
    "$issue_number" "$issue_title" "$issue_body" \
    "$pr_number" "$diff_stat" "$diff_content"

  # Append Co-Authored-By trailers for each PR approver
  local approver_login approver_name approver_email co_authored_by=""
  while IFS= read -r approver_login; do
    [[ -z "$approver_login" ]] && continue
    approver_name=$(gh api "users/${approver_login}" --jq '.name // .login' 2>/dev/null || echo "$approver_login")
    approver_email=$(gh api "users/${approver_login}" --jq '.email // ""' 2>/dev/null || echo "")
    [[ -z "$approver_email" ]] && approver_email="${approver_login}@users.noreply.github.com"
    co_authored_by+="Co-Authored-By: ${approver_name} <${approver_email}>"$'\n'
  done < <(gh pr view "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --json reviews --jq '[.reviews[] | select(.state=="APPROVED") | .author.login] | unique | .[]' 2>/dev/null)

  if [[ -n "$co_authored_by" ]]; then
    SQUASH_COMMIT_MESSAGE="${SQUASH_COMMIT_MESSAGE}

${co_authored_by%$'\n'}"
  fi

  local msg_file
  if [[ -n "${CUR_SESSION_DIR:-}" ]] && [[ -d "${CUR_SESSION_DIR:-}" ]]; then
    msg_file="${CUR_SESSION_DIR}/squash-msg.txt"
  else
    msg_file=$(mktemp)
  fi
  printf '%s\n' "$SQUASH_COMMIT_MESSAGE" > "$msg_file"

  local author_arg="${PRAUTO_GIT_AUTHOR_NAME} <${PRAUTO_GIT_AUTHOR_EMAIL}>"

  # Always rebuild as a single commit: reset to merge base and recommit
  git reset --soft "$merge_base" 2>/dev/null || {
    warn "PR #${pr_number}: git reset --soft failed."
    rm -f "$msg_file"
    return 1
  }
  git commit --author="$author_arg" --file="$msg_file" 2>/dev/null || {
    warn "PR #${pr_number}: git commit (squash) failed."
    rm -f "$msg_file"
    return 1
  }
  rm -f "$msg_file"

  # Force-push as the prauto account.
  # If GH_TOKEN is set, push over HTTPS with the token embedded in the URL so the
  # push authenticates as the prauto account regardless of the local remote protocol
  # (SSH remotes would otherwise use the system SSH key).
  #
  # --force-with-lease needs an explicit expected value when pushing to a URL
  # (rather than a named remote), because git can't infer the remote-tracking ref.
  local expected_sha
  expected_sha=$(git rev-parse "refs/remotes/origin/${pr_branch}" 2>/dev/null || echo "")
  local lease_flag="--force-with-lease"
  if [[ -n "$expected_sha" ]]; then
    lease_flag="--force-with-lease=refs/heads/${pr_branch}:${expected_sha}"
  fi

  if [[ -n "${GH_TOKEN:-}" ]]; then
    git push "$lease_flag" \
      "https://x-access-token:${GH_TOKEN}@github.com/${PRAUTO_GITHUB_REPO}.git" \
      "HEAD:refs/heads/${pr_branch}" || {
      warn "PR #${pr_number}: force-push failed (remote may have changed). Skipping."
      return 1
    }
  else
    git push "$lease_flag" origin "$pr_branch" || {
      warn "PR #${pr_number}: force-push failed (remote may have changed). Skipping."
      return 1
    }
  fi
  info "PR #${pr_number}: force-pushed squashed commit."

  # Extract the title of the final single commit (the squashed commit message first line).
  local final_commit_title
  final_commit_title=$(git log -1 --format='%s' HEAD 2>/dev/null || echo "$pr_title")

  # Update PR title to match the final squashed commit title.
  # Uses REST API instead of `gh pr edit` which requires read:org scope.
  gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${pr_number}" \
    -X PATCH -f title="$final_commit_title" --silent 2>/dev/null || \
    warn "PR #${pr_number}: failed to update PR title."
  info "PR #${pr_number}: updated title to '${final_commit_title}'."

  # Set prauto:done label on PR and linked issue (remove prauto:review).
  # Uses REST API — `gh pr edit` / `gh issue edit` require read:org scope.
  local target
  for target in "$pr_number" "$issue_number"; do
    gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${target}/labels" \
      -X POST -f "labels[]=${PRAUTO_GITHUB_LABEL_DONE}" --silent 2>/dev/null || \
      warn "#${target}: failed to add ${PRAUTO_GITHUB_LABEL_DONE} label."
    gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${target}/labels/${PRAUTO_GITHUB_LABEL_REVIEW}" \
      -X DELETE --silent 2>/dev/null || \
      warn "#${target}: failed to remove ${PRAUTO_GITHUB_LABEL_REVIEW} label."
  done

  info "PR #${pr_number}: marked as prauto:done (PR and issue #${issue_number}). NOT merged."
}

# Post Claude's response to reviewer comments as a PR comment.
# This provides a written answer to reviewer questions and explains changes made.
# Usage: post_review_response_comment <pr_number> <response_text>
post_review_response_comment() {
  local pr_number="$1"
  local response_text="$2"
  [[ -z "$response_text" ]] && return 0
  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): Review response

${response_text}" \
    2>/dev/null || warn "Failed to post review response on PR #${pr_number}."
}

# Look up the PR number for a given branch.
# Usage: get_pr_number_for_branch <branch>
# Sets: BRANCH_PR_NUMBER (empty if no PR found)
get_pr_number_for_branch() {
  local branch="$1"
  BRANCH_PR_NUMBER=$(gh pr list -R "$PRAUTO_GITHUB_REPO" \
    --head "$branch" --json number --jq '.[0].number // empty' 2>/dev/null) || BRANCH_PR_NUMBER=""
}

# Post test results as a PR comment.
# Uses a collapsible <details> section to keep the PR clean.
# Usage: post_test_results_comment <pr_number> <test_type> <exit_code> <output>
post_test_results_comment() {
  local pr_number="$1"
  local test_type="$2"
  local exit_code="$3"
  local output="$4"

  local status_label
  if [[ "$exit_code" -eq 0 ]]; then
    status_label="Passed"
  else
    status_label="Failed (exit code ${exit_code})"
  fi

  # Truncate output if too long (GitHub comment limit is 65536 chars)
  if [[ ${#output} -gt 60000 ]]; then
    output="${output:0:60000}
... (truncated)"
  fi

  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): ${test_type} Test Results — ${status_label}

<details>
<summary>${test_type} test output</summary>

\`\`\`
${output}
\`\`\`

</details>" \
    2>/dev/null || warn "Failed to post ${test_type} test results on PR #${pr_number}."
}

# Post a "feedback addressed" marker comment on a PR.
# check_review_pr() checks for this marker and skips the PR if present,
# preventing infinite re-pickup loops after addressing reviewer feedback.
# Usage: post_feedback_addressed_comment <pr_number>
post_feedback_addressed_comment() {
  local pr_number="$1"
  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): Reviewer feedback addressed." \
    2>/dev/null || warn "Failed to post feedback-addressed comment on PR #${pr_number}."
}
