# PR lifecycle operations for prauto.
# Source this file — do not execute directly.
# Requires: helpers.sh, state.sh, agent.sh, config loaded, gh/git available.

# scrub_secrets <text>
# Redact credentials before test output reaches a public PR comment. The E2E and
# api-wired suites exercise auth flows with DATASPOKE_DEV_* credentials, so a
# failing assertion can echo a token or a postgresql://user:***@host URL verbatim.
# Redacts (with ***REDACTED***):
#   - DATASPOKE_*= env assignments (the value, keeping the key for context)
#   - JWTs (three base64url segments)
#   - dsk_-prefixed API tokens
#   - user:password@ credentials embedded in URLs
#   - the worker's own GH_TOKEN / ANTHROPIC_API_KEY values
# sed -E / [:class:] / + are portable across BSD and GNU sed.
scrub_secrets() {
  local text="$1"
  text=$(printf '%s' "$text" | sed -E \
    -e 's/(DATASPOKE_[A-Z0-9_]*=)[^[:space:]]*/\1***REDACTED***/g' \
    -e 's/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/***REDACTED***/g' \
    -e 's/dsk_[A-Za-z0-9_-]+/***REDACTED***/g' \
    -e 's#://[^:@/[:space:]]+:[^@/[:space:]]+@#://***REDACTED***@#g')
  [[ -n "${GH_TOKEN:-}" ]] && text="${text//${GH_TOKEN}/***REDACTED***}"
  [[ -n "${ANTHROPIC_API_KEY:-}" ]] && text="${text//${ANTHROPIC_API_KEY}/***REDACTED***}"
  printf '%s' "$text"
}

# create_or_update_pr <issue_number> <issue_title> <branch>
create_or_update_pr() {
  local issue_number="$1" issue_title="$2" branch="$3"
  local existing_pr
  existing_pr=$(gh pr list -R "$PRAUTO_GITHUB_REPO" --head "$branch" \
    --json number --jq '.[0].number // empty' 2>/dev/null)

  if [[ -n "$existing_pr" ]]; then
    info "PR #${existing_pr} already exists for ${branch}. Adding update comment."
    local commit_log
    commit_log=$(git log --oneline "origin/${PRAUTO_BASE_BRANCH}..HEAD" 2>/dev/null || printf '(no commits)')
    gh pr comment "$existing_pr" -R "$PRAUTO_GITHUB_REPO" \
      --body "prauto(${PRAUTO_WORKER_ID}): Updated with new commits.

\`\`\`
${commit_log}
\`\`\`" 2>/dev/null || warn "Failed to comment on PR #${existing_pr}."
    return 0
  fi

  local commit_log
  commit_log=$(git log --oneline "origin/${PRAUTO_BASE_BRANCH}..HEAD" 2>/dev/null || printf '(no commits)')
  local pr_body="## Summary

Automated implementation for #${issue_number}.
Generated by \`prauto(${PRAUTO_WORKER_ID})\`.

## Changes

\`\`\`
${commit_log}
\`\`\`

---
*Generated by prauto -- autonomous PR worker*"

  local reviewer_flag=()
  [[ -n "${PRAUTO_REVIEWER:-}" ]] && reviewer_flag=(--reviewer "$PRAUTO_REVIEWER")

  info "Creating PR for issue #${issue_number}..."
  gh pr create -R "$PRAUTO_GITHUB_REPO" \
    --base "$PRAUTO_BASE_BRANCH" --head "$branch" \
    --title "$issue_title" --body "$pr_body" \
    --assignee "$PRAUTO_GITHUB_ACTOR" --label "${PRAUTO_GITHUB_LABEL_REVIEW}" \
    "${reviewer_flag[@]}" || error "Failed to create PR for ${branch}."
  info "PR created for issue #${issue_number}."
}

# check_review_pr <issue_number>
# For a prauto:review issue, determine the next action. Priority: squash-finalize
# (approved + mergeable + clean) > address feedback > waiting.
# Sets: REVIEW_PR_NUMBER/BRANCH/ACTION/TITLE/BODY, ACTIONABLE_COMMENTS.
# Returns 0 if actionable, 1 if waiting/no-pr.
check_review_pr() {
  local issue_number="$1"
  REVIEW_PR_BRANCH="${PRAUTO_BRANCH_PREFIX}I-${issue_number}"
  REVIEW_PR_ACTION=""

  local pr_list_json
  pr_list_json=$(gh pr list -R "$PRAUTO_GITHUB_REPO" --head "$REVIEW_PR_BRANCH" \
    --json number,title,body --jq '.[0] // empty' 2>/dev/null)
  [[ -z "$pr_list_json" ]] && return 1

  REVIEW_PR_NUMBER=$(printf '%s' "$pr_list_json" | jq -r '.number')
  REVIEW_PR_TITLE=$(printf '%s' "$pr_list_json" | jq -r '.title')
  REVIEW_PR_BODY=$(printf '%s' "$pr_list_json" | jq -r '.body // ""')

  local pr_detail
  pr_detail=$(gh pr view "$REVIEW_PR_NUMBER" -R "$PRAUTO_GITHUB_REPO" \
    --json mergeable,mergeStateStatus,reviews 2>/dev/null) || pr_detail=""

  # Priority 1: squash-ready (approved + MERGEABLE + CLEAN).
  if [[ -n "$pr_detail" ]] && fetch_org_members 2>/dev/null; then
    local mergeable merge_state approver
    mergeable=$(printf '%s' "$pr_detail" | jq -r '.mergeable')
    merge_state=$(printf '%s' "$pr_detail" | jq -r '.mergeStateStatus')
    approver=$(printf '%s' "$pr_detail" | jq -r --argjson members "$ORG_MEMBERS_JSON" '
      (.reviews // [])
      | map(select(.author.login as $a | $members | index($a) != null))
      | group_by(.author.login)
      | map(sort_by(.submittedAt) | last)
      | map(select(.state == "APPROVED"))
      | first // empty | .author.login // empty')
    if [[ -n "$approver" ]] && [[ "$mergeable" == "MERGEABLE" ]] && [[ "$merge_state" == "CLEAN" ]]; then
      REVIEW_PR_ACTION="squash_ready"
      info "PR #${REVIEW_PR_NUMBER}: approved by '${approver}', mergeable, clean → squash-ready."
      return 0
    fi
  fi

  # Priority 2: feedback-needed (unaddressed non-prauto comments).
  local pr_review_comments pr_issue_comments
  pr_review_comments=$(gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${REVIEW_PR_NUMBER}/comments" \
    --jq '[.[] | {id: .id, body: .body, user: .user.login, created_at: .created_at}]' 2>/dev/null || printf '[]')
  pr_issue_comments=$(gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${REVIEW_PR_NUMBER}/comments" \
    --jq '[.[] | {id: .id, body: .body, user: .user.login, created_at: .created_at}]' 2>/dev/null || printf '[]')

  local latest_prauto_body latest_prauto_time
  latest_prauto_body=$(printf '%s' "$pr_issue_comments" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" \
    '[.[] | select(.user == $actor)] | sort_by(.created_at) | last | .body // ""')
  latest_prauto_time=$(printf '%s' "$pr_issue_comments" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" \
    '[.[] | select(.user == $actor)] | sort_by(.created_at) | last | .created_at // ""')

  if printf '%s' "$latest_prauto_body" | grep -q "Reviewer feedback addressed"; then
    local newer_issue newer_reviews
    newer_issue=$(printf '%s' "$pr_issue_comments" | jq --arg actor "$PRAUTO_GITHUB_ACTOR" --arg ts "$latest_prauto_time" \
      '[.[] | select(.user != $actor) | select(.created_at > $ts)] | length')
    newer_reviews=$(printf '%s' "$pr_review_comments" | jq --arg ts "$latest_prauto_time" \
      '[.[] | select(.created_at > $ts)] | length')
    if [[ "$newer_issue" -eq 0 ]] && [[ "$newer_reviews" -eq 0 ]]; then
      info "PR #${REVIEW_PR_NUMBER}: feedback already addressed. Waiting."
      return 1
    fi
    info "PR #${REVIEW_PR_NUMBER}: new comments after marker. Re-evaluating."
  fi

  local all_comments
  all_comments=$(jq -s 'add' <<< "${pr_review_comments}${pr_issue_comments}" 2>/dev/null || printf '[]')
  local unaddressed unaddressed_count
  unaddressed=$(printf '%s' "$all_comments" | jq -r --arg worker "prauto(${PRAUTO_WORKER_ID})" \
    '[.[] | select(.body | startswith($worker) | not)]')
  unaddressed_count=$(printf '%s' "$unaddressed" | jq 'length')

  local has_review_signal=false
  if [[ -n "$pr_detail" ]]; then
    local has_review
    has_review=$(printf '%s' "$pr_detail" | jq \
      '[(.reviews // [])[] | select(.state == "CHANGES_REQUESTED" or .state == "COMMENTED")] | length > 0')
    [[ "$has_review" == "true" ]] && has_review_signal=true
  fi
  if [[ "$has_review_signal" == "false" ]] && [[ "$unaddressed_count" -gt 0 ]]; then
    local external_count
    external_count=$(printf '%s' "$unaddressed" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" \
      '[.[] | select(.user != $actor)] | length')
    [[ "$external_count" -gt 0 ]] && has_review_signal=true
  fi

  if [[ "$unaddressed_count" -gt 0 ]] && [[ "$has_review_signal" == "true" ]]; then
    ACTIONABLE_COMMENTS=$(printf '%s' "$all_comments" | jq -r --arg worker "prauto(${PRAUTO_WORKER_ID})" '
      [.[] | select(.body | startswith($worker) | not)]
      | map("Comment by \(.user):\n\(.body)")
      | join("\n\n---\n\n")')
    REVIEW_PR_ACTION="feedback_needed"
    info "PR #${REVIEW_PR_NUMBER}: unaddressed comments → feedback needed."
    return 0
  fi

  info "PR #${REVIEW_PR_NUMBER}: waiting for review."
  return 1
}

# squash_and_finalize_pr <pr_number> <pr_branch> <pr_title> <pr_body> <issue_number>
# Squash the PR branch into one commit, force-push, mark prauto:done. Does NOT
# merge or close — left to the human. Must be called from inside the worktree.
squash_and_finalize_pr() {
  local pr_number="$1" pr_branch="$2" pr_title="$3" pr_body="$4" issue_number="$5"

  export GIT_AUTHOR_NAME="$PRAUTO_GIT_AUTHOR_NAME" GIT_AUTHOR_EMAIL="$PRAUTO_GIT_AUTHOR_EMAIL"
  export GIT_COMMITTER_NAME="$PRAUTO_GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$PRAUTO_GIT_AUTHOR_EMAIL"

  git fetch origin "$PRAUTO_BASE_BRANCH" 2>/dev/null || { warn "PR #${pr_number}: git fetch failed."; return 1; }
  git rebase "origin/${PRAUTO_BASE_BRANCH}" 2>/dev/null || {
    warn "PR #${pr_number}: rebase failed. Aborting."
    git rebase --abort 2>/dev/null || true
    return 1
  }

  local merge_base
  merge_base=$(git merge-base HEAD "origin/${PRAUTO_BASE_BRANCH}" 2>/dev/null) || {
    warn "PR #${pr_number}: could not find merge base."
    return 1
  }

  local issue_title issue_body diff_stat diff_content
  issue_title=$(gh issue view "$issue_number" -R "$PRAUTO_GITHUB_REPO" --json title --jq '.title // ""' 2>/dev/null || printf '')
  issue_body=$(gh issue view "$issue_number" -R "$PRAUTO_GITHUB_REPO" --json body --jq '.body // ""' 2>/dev/null || printf '')
  diff_stat=$(git diff --stat "${merge_base}..HEAD" 2>/dev/null || printf '(no diff stat)')
  diff_content=$(git diff "${merge_base}..HEAD" 2>/dev/null || printf '(no diff)')

  generate_squash_commit_message "$issue_number" "$issue_title" "$issue_body" "$pr_number" "$diff_stat" "$diff_content"

  local approver_login approver_name approver_email co_authored_by=""
  while IFS= read -r approver_login; do
    [[ -z "$approver_login" ]] && continue
    approver_name=$(gh api "users/${approver_login}" --jq '.name // .login' 2>/dev/null || printf '%s' "$approver_login")
    approver_email=$(gh api "users/${approver_login}" --jq '.email // ""' 2>/dev/null || printf '')
    [[ -z "$approver_email" ]] && approver_email="${approver_login}@users.noreply.github.com"
    co_authored_by+="Co-Authored-By: ${approver_name} <${approver_email}>"$'\n'
  done < <(gh pr view "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --json reviews --jq '[.reviews[] | select(.state=="APPROVED") | .author.login] | unique | .[]' 2>/dev/null)

  [[ -n "$co_authored_by" ]] && SQUASH_COMMIT_MESSAGE="${SQUASH_COMMIT_MESSAGE}

${co_authored_by%$'\n'}"

  local msg_file
  if [[ -n "${CUR_SESSION_DIR:-}" ]] && [[ -d "${CUR_SESSION_DIR:-}" ]]; then
    msg_file="${CUR_SESSION_DIR}/squash-msg.txt"
  else
    msg_file=$(mktemp)
  fi
  printf '%s\n' "$SQUASH_COMMIT_MESSAGE" > "$msg_file"

  local author_arg="${PRAUTO_GIT_AUTHOR_NAME} <${PRAUTO_GIT_AUTHOR_EMAIL}>"
  git reset --soft "$merge_base" 2>/dev/null || { warn "PR #${pr_number}: git reset --soft failed."; rm -f "$msg_file"; return 1; }
  git commit --author="$author_arg" --file="$msg_file" 2>/dev/null || {
    warn "PR #${pr_number}: git commit (squash) failed."; rm -f "$msg_file"; return 1
  }
  rm -f "$msg_file"

  # Force-push with lease. With GH_TOKEN set, push over HTTPS with the token
  # embedded so the push authenticates as the prauto account regardless of the
  # local remote protocol (SSH remotes would otherwise use the system key).
  local expected_sha lease_flag="--force-with-lease"
  expected_sha=$(git rev-parse "refs/remotes/origin/${pr_branch}" 2>/dev/null || printf '')
  [[ -n "$expected_sha" ]] && lease_flag="--force-with-lease=refs/heads/${pr_branch}:${expected_sha}"

  if [[ -n "${GH_TOKEN:-}" ]]; then
    local push_url="https://x-access-token:${GH_TOKEN}@github.com/${PRAUTO_GITHUB_REPO}.git"
    git push "$lease_flag" "$push_url" "HEAD:refs/heads/${pr_branch}" 2>/dev/null || {
      warn "PR #${pr_number}: force-push failed. Skipping."
      return 1
    }
  else
    git push "$lease_flag" origin "$pr_branch" 2>/dev/null || {
      warn "PR #${pr_number}: force-push failed. Skipping."
      return 1
    }
  fi
  info "PR #${pr_number}: force-pushed squashed commit."

  local final_commit_title
  final_commit_title=$(git log -1 --format='%s' HEAD 2>/dev/null || printf '%s' "$pr_title")
  gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${pr_number}" \
    -X PATCH -f title="$final_commit_title" --silent 2>/dev/null \
    || warn "PR #${pr_number}: failed to update PR title."

  local target
  for target in "$pr_number" "$issue_number"; do
    gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${target}/labels" \
      -X POST -f "labels[]=${PRAUTO_GITHUB_LABEL_DONE}" --silent 2>/dev/null \
      || warn "#${target}: failed to add ${PRAUTO_GITHUB_LABEL_DONE} label."
    gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${target}/labels/${PRAUTO_GITHUB_LABEL_REVIEW}" \
      -X DELETE --silent 2>/dev/null \
      || warn "#${target}: failed to remove ${PRAUTO_GITHUB_LABEL_REVIEW} label."
  done
  info "PR #${pr_number}: marked prauto:done (PR and issue #${issue_number}). NOT merged."
}

# post_review_response_comment <pr_number> <response_text>
post_review_response_comment() {
  local pr_number="$1" response_text="$2"
  [[ -z "$response_text" ]] && return 0
  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): Review response

${response_text}" \
    2>/dev/null || warn "Failed to post review response on PR #${pr_number}."
}

# get_pr_number_for_branch <branch>  — Sets: BRANCH_PR_NUMBER (empty if none).
get_pr_number_for_branch() {
  local branch="$1"
  BRANCH_PR_NUMBER=$(gh pr list -R "$PRAUTO_GITHUB_REPO" --head "$branch" \
    --json number --jq '.[0].number // empty' 2>/dev/null) || BRANCH_PR_NUMBER=""
}

# post_test_results_comment <pr_number> <test_type> <exit_code> <output>
post_test_results_comment() {
  local pr_number="$1" test_type="$2" exit_code="$3" output="$4"
  output=$(scrub_secrets "$output")

  local status_label
  if [[ "$exit_code" -eq 0 ]]; then status_label="Passed"; else status_label="Failed (exit code ${exit_code})"; fi
  if [[ ${#output} -gt 60000 ]]; then output="${output:0:60000}
... (truncated)"; fi

  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): ${test_type} Test Results — ${status_label}

<details>
<summary>${test_type} test output</summary>

\`\`\`
${output}
\`\`\`

</details>" \
    2>/dev/null || warn "Failed to post ${test_type} test results on PR #${pr_number}."
}

# post_feedback_addressed_comment <pr_number>
post_feedback_addressed_comment() {
  local pr_number="$1"
  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): Reviewer feedback addressed." 2>/dev/null \
    || warn "Failed to post feedback-addressed comment on PR #${pr_number}."
}
