# PR lifecycle operations for prauto.
# Source this file — do not execute directly.
# Requires: helpers.sh sourced, state.sh sourced, claude.sh sourced, config loaded, gh/git available.

# Create or update a PR for the given issue.
# Usage: create_or_update_pr <issue_number> <issue_title> <branch>
create_or_update_pr() {
  local issue_number="$1"
  local issue_title="$2"
  local branch="$3"

  # Check for existing PR
  local existing_pr
  existing_pr=$(gh pr list \
    -R "$PRAUTO_GITHUB_REPO" \
    --head "$branch" \
    --json number \
    --jq '.[0].number // empty' 2>/dev/null)

  if [[ -n "$existing_pr" ]]; then
    info "PR #${existing_pr} already exists for ${branch}. Adding update comment."
    local commit_log
    commit_log=$(git log --oneline "origin/${PRAUTO_BASE_BRANCH}..HEAD" 2>/dev/null || echo "(no commits)")
    gh pr comment "$existing_pr" -R "$PRAUTO_GITHUB_REPO" \
      --body "prauto(${PRAUTO_WORKER_ID}): Updated with new commits.

\`\`\`
${commit_log}
\`\`\`" 2>/dev/null || warn "Failed to comment on PR #${existing_pr}."
    return 0
  fi

  # Generate PR body
  local commit_log
  commit_log=$(git log --oneline "origin/${PRAUTO_BASE_BRANCH}..HEAD" 2>/dev/null || echo "(no commits)")

  local pr_body
  pr_body="## Summary

Automated implementation for #${issue_number}.
Generated by \`prauto(${PRAUTO_WORKER_ID})\` using Claude Code CLI.

## Changes

\`\`\`
${commit_log}
\`\`\`

## Test plan

- [ ] Review automated changes
- [ ] Verify tests pass in CI
- [ ] Check spec compliance

---
*Generated by prauto -- autonomous PR worker*"

  # Build optional flags
  local reviewer_flag=()
  if [[ -n "${PRAUTO_REVIEWER:-}" ]]; then
    reviewer_flag=(--reviewer "$PRAUTO_REVIEWER")
  fi

  info "Creating PR for issue #${issue_number}..."
  gh pr create \
    -R "$PRAUTO_GITHUB_REPO" \
    --base "$PRAUTO_BASE_BRANCH" \
    --head "$branch" \
    --title "${issue_title}" \
    --body "$pr_body" \
    --assignee "${PRAUTO_GITHUB_ACTOR}" \
    --label "${PRAUTO_GITHUB_LABEL_REVIEW}" \
    "${reviewer_flag[@]}" || error "Failed to create PR for ${branch}."

  info "PR created for issue #${issue_number}."
}

# Find open PRs with unaddressed reviewer comments.
# Sets: ACTIONABLE_PR_NUMBER, ACTIONABLE_PR_BRANCH, ACTIONABLE_PR_ISSUE, ACTIONABLE_COMMENTS
# Returns 0 if found, 1 if none.
find_actionable_prs() {
  local prs_json
  prs_json=$(gh pr list \
    -R "$PRAUTO_GITHUB_REPO" \
    --state open \
    --json number,headRefName,reviews,labels,assignees \
    --limit 50 2>/dev/null) || {
    warn "Failed to list PRs."
    return 1
  }

  # Filter PRs on prauto branches that have prauto:review label and are assigned to this worker
  local prauto_prs
  prauto_prs=$(echo "$prs_json" | jq -r \
    --arg prefix "$PRAUTO_BRANCH_PREFIX" \
    --arg review_label "$PRAUTO_GITHUB_LABEL_REVIEW" \
    --arg actor "$PRAUTO_GITHUB_ACTOR" '
    [.[] | select(
      (.headRefName | startswith($prefix)) and
      (.labels | map(.name) | index($review_label) != null) and
      (.assignees | map(.login) | index($actor) != null)
    )]
    | sort_by(.number)
  ')

  local pr_count
  pr_count=$(echo "$prauto_prs" | jq 'length')

  if [[ "$pr_count" -eq 0 ]]; then
    return 1
  fi

  # Check each PR for unaddressed reviewer comments
  local i=0
  while [[ "$i" -lt "$pr_count" ]]; do
    local pr_number
    pr_number=$(echo "$prauto_prs" | jq -r ".[$i].number")
    local pr_branch
    pr_branch=$(echo "$prauto_prs" | jq -r ".[$i].headRefName")

    # Verify linked issue is still open (GitHub SSOT)
    local issue_from_branch="${pr_branch#${PRAUTO_BRANCH_PREFIX}I-}"
    local linked_issue_state
    linked_issue_state=$(gh issue view "$issue_from_branch" -R "$PRAUTO_GITHUB_REPO" \
      --json state --jq '.state' 2>/dev/null || echo "UNKNOWN")
    if [[ "$linked_issue_state" != "OPEN" ]]; then
      info "PR #${pr_number}: linked issue #${issue_from_branch} is ${linked_issue_state}. Skipping."
      i=$((i + 1)); continue
    fi

    # Get formal review states (CHANGES_REQUESTED / COMMENTED)
    local reviews
    reviews=$(gh pr view "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
      --json reviews \
      --jq '[.reviews[] | select(.state == "CHANGES_REQUESTED" or .state == "COMMENTED")] | sort_by(.submittedAt) | last' \
      2>/dev/null)

    # Get inline PR review comments (code-level)
    local pr_review_comments
    pr_review_comments=$(gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${pr_number}/comments" \
      --jq '[.[] | {id: .id, body: .body, user: .user.login, created_at: .created_at}]' \
      2>/dev/null || echo "[]")

    # Get issue-level comments on the PR (conversation tab)
    local pr_issue_comments
    pr_issue_comments=$(gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${pr_number}/comments" \
      --jq '[.[] | {id: .id, body: .body, user: .user.login, created_at: .created_at}]' \
      2>/dev/null || echo "[]")

    # Skip if latest prauto comment is a "feedback addressed" marker
    local latest_prauto
    latest_prauto=$(echo "$pr_issue_comments" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" '
      [.[] | select(.user == $actor)] | sort_by(.created_at) | last | .body // ""
    ')
    if echo "$latest_prauto" | grep -q "Reviewer feedback addressed"; then
      info "PR #${pr_number}: feedback already addressed. Skipping."
      i=$((i + 1))
      continue
    fi

    # Merge both comment sources
    local all_comments
    all_comments=$(jq -s 'add' <<< "${pr_review_comments}${pr_issue_comments}" 2>/dev/null || echo "[]")

    # Find non-prauto comments (reviewer feedback)
    local unaddressed
    unaddressed=$(echo "$all_comments" | jq -r --arg worker "prauto(${PRAUTO_WORKER_ID})" '
      [.[] | select(.body | startswith($worker) | not)]
    ')

    local unaddressed_count
    unaddressed_count=$(echo "$unaddressed" | jq 'length')

    # Actionable if there are unaddressed comments AND either:
    # - a formal review exists (CHANGES_REQUESTED/COMMENTED), OR
    # - issue-level comments from non-prauto users exist (reviewer used conversation tab)
    local has_review_signal=false
    if [[ -n "$reviews" ]] && [[ "$reviews" != "null" ]]; then
      has_review_signal=true
    fi
    if [[ "$has_review_signal" == "false" ]] && [[ "$unaddressed_count" -gt 0 ]]; then
      # Check if any unaddressed comment is from someone other than the PR author (prauto actor)
      local external_count
      external_count=$(echo "$unaddressed" | jq -r --arg actor "$PRAUTO_GITHUB_ACTOR" '
        [.[] | select(.user != $actor)] | length
      ')
      if [[ "$external_count" -gt 0 ]]; then
        has_review_signal=true
      fi
    fi

    if [[ "$unaddressed_count" -gt 0 ]] && [[ "$has_review_signal" == "true" ]]; then
      ACTIONABLE_PR_NUMBER="$pr_number"
      ACTIONABLE_PR_BRANCH="$pr_branch"
      # Extract issue number from branch name (prauto/I-42 → 42)
      ACTIONABLE_PR_ISSUE="${pr_branch#${PRAUTO_BRANCH_PREFIX}I-}"
      ACTIONABLE_COMMENTS=$(echo "$all_comments" | jq -r --arg worker "prauto(${PRAUTO_WORKER_ID})" '
        [.[] | select(.body | startswith($worker) | not)]
        | map("Comment by \(.user):\n\(.body)")
        | join("\n\n---\n\n")
      ')
      info "Found actionable PR #${pr_number} with unaddressed comments."
      return 0
    fi

    i=$((i + 1))
  done

  return 1
}

# Find prauto-owned PRs that are approved by an org member and merge-ready.
# Sets: MERGEABLE_PR_NUMBER, MERGEABLE_PR_BRANCH, MERGEABLE_PR_TITLE,
#       MERGEABLE_PR_BODY, MERGEABLE_PR_ISSUE
# Returns 0 if found, 1 if none.
find_mergeable_prs() {
  # Fetch org members for approval check
  if ! fetch_org_members; then
    warn "Cannot check PR approvals without org member list."
    return 1
  fi
  local members_json="$ORG_MEMBERS_JSON"

  local prs_json
  prs_json=$(gh pr list -R "$PRAUTO_GITHUB_REPO" --state open \
    --json number,headRefName,title,body,labels,assignees --limit 50 2>/dev/null) || {
    warn "Failed to list PRs for merge check."
    return 1
  }

  local pr_numbers
  pr_numbers=$(echo "$prs_json" | jq -r \
    --arg prefix "$PRAUTO_BRANCH_PREFIX" \
    --arg review_label "$PRAUTO_GITHUB_LABEL_REVIEW" \
    --arg actor "$PRAUTO_GITHUB_ACTOR" '
    [.[] | select(
      (.headRefName | startswith($prefix)) and
      (.labels | map(.name) | index($review_label) != null) and
      (.assignees | map(.login) | index($actor) != null)
    )]
    | sort_by(.number) | .[].number')
  [[ -z "$pr_numbers" ]] && return 1

  while IFS= read -r pr_number; do
    [[ -z "$pr_number" ]] && continue
    local pr_branch pr_title pr_body
    pr_branch=$(echo "$prs_json" | jq -r --argjson n "$pr_number" '.[] | select(.number==$n) | .headRefName')
    pr_title=$(echo "$prs_json"  | jq -r --argjson n "$pr_number" '.[] | select(.number==$n) | .title')
    pr_body=$(echo "$prs_json"   | jq -r --argjson n "$pr_number" '.[] | select(.number==$n) | .body // ""')

    local pr_detail
    pr_detail=$(gh pr view "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
      --json mergeable,mergeStateStatus,reviews 2>/dev/null) || continue

    local mergeable merge_state
    mergeable=$(echo "$pr_detail"    | jq -r '.mergeable')
    merge_state=$(echo "$pr_detail"  | jq -r '.mergeStateStatus')

    # Check if any org member left an APPROVED review (latest review per member)
    local is_approved approver
    approver=$(echo "$pr_detail" | jq -r --argjson members "$members_json" '
      (.reviews // [])
      | map(select(.author.login as $a | $members | index($a) != null))
      | group_by(.author.login)
      | map(sort_by(.submittedAt) | last)
      | map(select(.state == "APPROVED"))
      | first // empty
      | .author.login // empty')
    is_approved=$([[ -n "$approver" ]] && echo "true" || echo "false")

    if [[ "$is_approved" == "true" ]] && \
       [[ "$mergeable" == "MERGEABLE" ]] && \
       [[ "$merge_state" == "CLEAN" ]]; then
      MERGEABLE_PR_NUMBER="$pr_number"
      MERGEABLE_PR_BRANCH="$pr_branch"
      MERGEABLE_PR_TITLE="$pr_title"
      MERGEABLE_PR_BODY="$pr_body"
      MERGEABLE_PR_ISSUE="${pr_branch#${PRAUTO_BRANCH_PREFIX}I-}"
      info "Found merge-ready PR #${pr_number} approved by org member '${approver}'."
      return 0
    fi
  done <<< "$pr_numbers"
  return 1
}

# Squash all commits on the PR branch into one, force-push, and mark as done.
# Does NOT merge the PR or close the issue — leaves that for the human.
# Rebuilds the commit message via Claude based on the issue description and git diff.
# Must be called from inside the worktree (checkout_branch_worktree already ran).
# Usage: squash_and_finalize_pr <pr_number> <pr_branch> <pr_title> <pr_body> <issue_number>
squash_and_finalize_pr() {
  local pr_number="$1"
  local pr_branch="$2"
  local pr_title="$3"
  local pr_body="$4"
  local issue_number="$5"

  # Export git identity for ALL subprocesses (rebase, commit, amend).
  # Exporting here (not per-command) ensures git's internal re-invocations also
  # pick up the prauto identity rather than the system git config.
  export GIT_AUTHOR_NAME="$PRAUTO_GIT_AUTHOR_NAME"
  export GIT_AUTHOR_EMAIL="$PRAUTO_GIT_AUTHOR_EMAIL"
  export GIT_COMMITTER_NAME="$PRAUTO_GIT_AUTHOR_NAME"
  export GIT_COMMITTER_EMAIL="$PRAUTO_GIT_AUTHOR_EMAIL"

  # Fetch base branch
  git fetch origin "$PRAUTO_BASE_BRANCH" 2>/dev/null || {
    warn "PR #${pr_number}: git fetch failed."
    return 1
  }

  # Rebase onto base branch
  if ! git rebase "origin/${PRAUTO_BASE_BRANCH}" 2>/dev/null; then
    warn "PR #${pr_number}: rebase onto origin/${PRAUTO_BASE_BRANCH} failed. Aborting."
    git rebase --abort 2>/dev/null || true
    return 1
  fi

  # Find merge base and count commits to squash
  local merge_base
  merge_base=$(git merge-base HEAD "origin/${PRAUTO_BASE_BRANCH}" 2>/dev/null) || {
    warn "PR #${pr_number}: could not find merge base."
    return 1
  }

  # Fetch issue description for commit message generation
  local issue_title issue_body
  issue_title=$(gh issue view "$issue_number" -R "$PRAUTO_GITHUB_REPO" \
    --json title --jq '.title // ""' 2>/dev/null || echo "")
  issue_body=$(gh issue view "$issue_number" -R "$PRAUTO_GITHUB_REPO" \
    --json body --jq '.body // ""' 2>/dev/null || echo "")

  # Gather diff info for Claude
  local diff_stat diff_content
  diff_stat=$(git diff --stat "${merge_base}..HEAD" 2>/dev/null || echo "(no diff stat)")
  diff_content=$(git diff "${merge_base}..HEAD" 2>/dev/null || echo "(no diff)")

  # Generate commit message via Claude (Phase 4)
  generate_squash_commit_message \
    "$issue_number" "$issue_title" "$issue_body" \
    "$pr_number" "$diff_stat" "$diff_content"

  # Append Co-Authored-By trailers for each PR approver
  local approver_login approver_name approver_email co_authored_by=""
  while IFS= read -r approver_login; do
    [[ -z "$approver_login" ]] && continue
    approver_name=$(gh api "users/${approver_login}" --jq '.name // .login' 2>/dev/null || echo "$approver_login")
    approver_email=$(gh api "users/${approver_login}" --jq '.email // ""' 2>/dev/null || echo "")
    [[ -z "$approver_email" ]] && approver_email="${approver_login}@users.noreply.github.com"
    co_authored_by+="Co-Authored-By: ${approver_name} <${approver_email}>"$'\n'
  done < <(gh pr view "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --json reviews --jq '[.reviews[] | select(.state=="APPROVED") | .author.login] | unique | .[]' 2>/dev/null)

  if [[ -n "$co_authored_by" ]]; then
    SQUASH_COMMIT_MESSAGE="${SQUASH_COMMIT_MESSAGE}

${co_authored_by%$'\n'}"
  fi

  local msg_file
  msg_file=$(mktemp /tmp/prauto-squash-msg-XXXXXX)
  printf '%s\n' "$SQUASH_COMMIT_MESSAGE" > "$msg_file"

  local author_arg="${PRAUTO_GIT_AUTHOR_NAME} <${PRAUTO_GIT_AUTHOR_EMAIL}>"

  # Always rebuild as a single commit: reset to merge base and recommit
  git reset --soft "$merge_base" 2>/dev/null || {
    warn "PR #${pr_number}: git reset --soft failed."
    rm -f "$msg_file"
    return 1
  }
  git commit --author="$author_arg" --file="$msg_file" 2>/dev/null || {
    warn "PR #${pr_number}: git commit (squash) failed."
    rm -f "$msg_file"
    return 1
  }
  rm -f "$msg_file"

  # Force-push as the prauto account.
  # If GH_TOKEN is set, push over HTTPS with the token embedded in the URL so the
  # push authenticates as the prauto account regardless of the local remote protocol
  # (SSH remotes would otherwise use the system SSH key).
  #
  # --force-with-lease needs an explicit expected value when pushing to a URL
  # (rather than a named remote), because git can't infer the remote-tracking ref.
  local expected_sha
  expected_sha=$(git rev-parse "refs/remotes/origin/${pr_branch}" 2>/dev/null || echo "")
  local lease_flag="--force-with-lease"
  if [[ -n "$expected_sha" ]]; then
    lease_flag="--force-with-lease=refs/heads/${pr_branch}:${expected_sha}"
  fi

  if [[ -n "${GH_TOKEN:-}" ]]; then
    git push "$lease_flag" \
      "https://x-access-token:${GH_TOKEN}@github.com/${PRAUTO_GITHUB_REPO}.git" \
      "HEAD:refs/heads/${pr_branch}" || {
      warn "PR #${pr_number}: force-push failed (remote may have changed). Skipping."
      return 1
    }
  else
    git push "$lease_flag" origin "$pr_branch" || {
      warn "PR #${pr_number}: force-push failed (remote may have changed). Skipping."
      return 1
    }
  fi
  info "PR #${pr_number}: force-pushed squashed commit."

  # Extract the title of the final single commit (the squashed commit message first line).
  local final_commit_title
  final_commit_title=$(git log -1 --format='%s' HEAD 2>/dev/null || echo "$pr_title")

  # Update PR title to match the final squashed commit title.
  # Uses REST API instead of `gh pr edit` which requires read:org scope.
  gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${pr_number}" \
    -X PATCH -f title="$final_commit_title" --silent 2>/dev/null || \
    warn "PR #${pr_number}: failed to update PR title."
  info "PR #${pr_number}: updated title to '${final_commit_title}'."

  # Set prauto:done label on PR and linked issue (remove prauto:review).
  # Uses REST API — `gh pr edit` / `gh issue edit` require read:org scope.
  local target
  for target in "$pr_number" "$issue_number"; do
    gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${target}/labels" \
      -X POST -f "labels[]=${PRAUTO_GITHUB_LABEL_DONE}" --silent 2>/dev/null || \
      warn "#${target}: failed to add ${PRAUTO_GITHUB_LABEL_DONE} label."
    gh api "repos/${PRAUTO_GITHUB_REPO}/issues/${target}/labels/${PRAUTO_GITHUB_LABEL_REVIEW}" \
      -X DELETE --silent 2>/dev/null || \
      warn "#${target}: failed to remove ${PRAUTO_GITHUB_LABEL_REVIEW} label."
  done

  info "PR #${pr_number}: marked as prauto:done (PR and issue #${issue_number}). NOT merged."
}

# Reply to reviewer comments on a PR with idempotency.
# Usage: reply_to_comments <pr_number> <comment_ids_csv>
reply_to_comments() {
  local pr_number="$1"
  local comment_ids="$2"

  IFS=',' read -ra ids <<< "$comment_ids"
  for comment_id in "${ids[@]}"; do
    [[ -z "$comment_id" ]] && continue

    # Local cache check (fast path)
    if [[ -f "$JOB_FILE" ]]; then
      local already_replied
      already_replied=$(jq -r --arg id "$comment_id" '.replied_comment_ids | index($id) // empty' "$JOB_FILE" 2>/dev/null)
      if [[ -n "$already_replied" ]]; then
        info "Comment ${comment_id} already replied to (local). Skipping."
        continue
      fi
    fi
    # GitHub fallback (SSOT)
    local existing_reply
    existing_reply=$(gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${pr_number}/comments" \
      --jq "[.[] | select(.in_reply_to_id == ${comment_id}) | select(.body | startswith(\"prauto(${PRAUTO_WORKER_ID}):\"))] | length" \
      2>/dev/null || echo "0")
    if [[ "$existing_reply" -gt 0 ]]; then
      info "Comment ${comment_id} already replied to (GitHub). Skipping."
      [[ -f "$JOB_FILE" ]] && add_replied_comment_id "$comment_id"
      continue
    fi

    # Record ID before posting (crash safety)
    add_replied_comment_id "$comment_id"

    # Post reply
    gh api "repos/${PRAUTO_GITHUB_REPO}/pulls/${pr_number}/comments/${comment_id}/replies" \
      -f body="prauto(${PRAUTO_WORKER_ID}): Addressed feedback in latest commits." \
      2>/dev/null || warn "Failed to reply to comment ${comment_id} on PR #${pr_number}."
  done
}

# Post a "feedback addressed" marker comment on a PR.
# find_actionable_prs() checks for this marker and skips the PR if present,
# preventing infinite re-pickup loops after addressing reviewer feedback.
# Usage: post_feedback_addressed_comment <pr_number>
post_feedback_addressed_comment() {
  local pr_number="$1"
  gh pr comment "$pr_number" -R "$PRAUTO_GITHUB_REPO" \
    --body "prauto(${PRAUTO_WORKER_ID}): Reviewer feedback addressed." \
    2>/dev/null || warn "Failed to post feedback-addressed comment on PR #${pr_number}."
}
